// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_trBxLvxQeVPazzPFPPheZUys9MKjAis',
    appId: '1:175636859094:web:7fa381269a57ac6deb2177',
    messagingSenderId: '175636859094',
    projectId: 'urja-buddyyy',
    authDomain: 'urja-buddyyy.firebaseapp.com',
    storageBucket: 'urja-buddyyy.firebasestorage.app',
    measurementId: 'G-C70EN8VLTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'replace-with-your-api-key',
    appId: 'replace-with-your-app-id',
    messagingSenderId: 'replace-with-your-sender-id',
    projectId: 'replace-with-your-project-id',
    storageBucket: 'replace-with-your-storage-bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'replace-with-your-api-key',
    appId: 'replace-with-your-app-id',
    messagingSenderId: 'replace-with-your-sender-id',
    projectId: 'replace-with-your-project-id',
    storageBucket: 'replace-with-your-storage-bucket',
    iosBundleId: 'com.example.urjaBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'replace-with-your-api-key',
    appId: 'replace-with-your-app-id',
    messagingSenderId: 'replace-with-your-sender-id',
    projectId: 'replace-with-your-project-id',
    storageBucket: 'replace-with-your-storage-bucket',
    iosBundleId: 'com.example.urjaBuddy',
  );
}
